test_that("DuckDB is the default store", {
  old <- Sys.getenv("DV_DB_DRIVER"); on.exit(Sys.setenv(DV_DB_DRIVER = old))
  Sys.unsetenv("DV_DB_DRIVER")
  expect_equal(db_driver(), "duckdb")
})

test_that("schema is created idempotently", {
  con <- test_con()
  db_init(con)
  expect_true(all(names(digitalvalue:::db_schema) %in% DBI::dbListTables(con)))
})

test_that("registration records the initiative and its RICE at once", {
  cfg <- test_cfg()
  con <- test_con()
  id <- reg(con, cfg, "Test")
  expect_equal(id, "DV-0001")
  expect_equal(db_get_initiatives(con, id)$status, "Registered")
  rc <- db_get_rice(con)
  expect_equal(rc$initiative_id, id)
  expect_equal(rc$scored_by, "u1")
  expect_equal(db_next_initiative_id(con), "DV-0002")
  expect_error(db_register_initiative(con, list(name = " "), rice_assess(10, "M", "Low", "S", cfg)),
               "required")
  expect_equal(nrow(db_get_initiatives(con)), 1)
  expect_equal(nrow(db_get_rice(con)), 1)
})

test_that("initiative update, status changes and history", {
  cfg <- test_cfg()
  con <- test_con()
  id <- reg(con, cfg)
  db_update_initiative(con, id, list(name = "Renamed", cost_mm_usd = 2, status = "hack"))
  i <- db_get_initiatives(con, id)
  expect_equal(i$name, "Renamed")
  expect_equal(i$cost_mm_usd, 2)
  expect_equal(i$status, "Registered")
  expect_true(db_set_status(con, id, "Rejected", "u1", "no"))
  expect_false(db_set_status(con, id, "Rejected", "u1"))
  expect_equal(db_get_status_history(con)$to_status, c("Registered", "Rejected"))
  expect_error(db_set_status(con, "DV-9999", "Ready"), "Unknown")
})

test_that("4M lines, expert reviews with 4M figures and audits with adoption", {
  cfg <- test_cfg()
  con <- test_con()
  id <- reg(con, cfg)
  db_save_rice(con, id, rice_assess(1000, "L", "High", "M", cfg))
  expect_equal(nrow(db_get_rice(con)), 1)

  lid <- db_add_m4_line(con, id, m4_calculate("p_jobs_success", list(), cfg), "workovers")
  l <- db_get_m4_lines(con, id)
  expect_equal(jsonlite::fromJSON(l$params_json)$n_jobs, 10)
  expect_equal(l$comment, "workovers")

  v <- list(P = 25, R = 0.1, category = "1P", M = 0.2, T = 3)
  db_add_review(con, id, "Approve", v, m4_value(v, cfg)$total, 0.6, "ok", "boss")
  expect_error(db_add_review(con, id, "Maybe"))
  r <- db_get_reviews(con, id)
  expect_equal(r$p_bopd, 25)
  expect_equal(r$r_category, "1P")
  expect_equal(r$value_mm_usd, m4_value(v, cfg)$total)

  a <- list(P = 20, R = 0, M = 0.1, T = 2, category = "2P")
  db_add_audit(con, id, a, 75, 0.5, 1, "fine", "boss")
  au <- db_get_audits(con, id)
  expect_equal(au$adoption_pct, 75)
  expect_equal(au$realization_pct, 50)

  pf <- db_portfolio(con)
  expect_equal(pf$plan_p, 30)
  expect_equal(pf$plan_lines, 1)
  expect_equal(pf$review_decision, "Approve")
  expect_equal(pf$review_p, 25)
  expect_equal(pf$actual_p, 20)
  expect_equal(pf$adoption_pct, 75)
  expect_equal(pf$audited_value_mm_usd, 0.5)

  db_delete_m4_line(con, lid)
  expect_equal(nrow(db_get_m4_lines(con, id)), 0)
})

test_that("latest review wins in the portfolio view", {
  cfg <- test_cfg()
  con <- test_con()
  id <- reg(con, cfg)
  db_add_review(con, id, "Rework", time = Sys.time() - 100)
  db_add_review(con, id, "Approve", time = Sys.time())
  expect_equal(db_portfolio(con)$review_decision, "Approve")
})

test_that("value model versions: publish, activate, roundtrip", {
  cfg <- test_cfg()
  con <- test_con()
  set.seed(2)
  d <- data.frame(log_y = rnorm(12), reach_value = runif(12, 1, 4), log_effort = log(runif(12, .5, 8)))
  fit <- stats::lm(log_y ~ reach_value + log_effort, data = d)
  rec <- model_record(fit, "rice_to_review", "multivariable", 0.8)
  m1 <- db_publish_value_model(con, rec, "first", "boss", Sys.time() - 10)
  m2 <- db_publish_value_model(con, rec, "second", "boss")
  v <- db_get_value_models(con, "rice_to_review")
  expect_equal(nrow(v), 2)
  expect_equal(sum(v$active), 1)
  expect_equal(db_active_value_model(con, "rice_to_review")$model_id, m2)
  db_activate_value_model(con, m1)
  back <- db_active_value_model(con, "rice_to_review")
  expect_equal(back$model_id, m1)
  expect_equal(unname(back$coef), unname(stats::coef(fit)), tolerance = 1e-10)
  expect_equal(unname(back$vcov), unname(stats::vcov(fit)), tolerance = 1e-10)
  expect_null(db_active_value_model(con, "review_to_audit"))
  expect_error(db_activate_value_model(con, "nope"), "Unknown")
})

test_that("event log append and read", {
  con <- test_con()
  ev <- normalize_raw_batch('[{"ts":"2026-01-01T10:00:00.000Z","name":"nav","value":"initiative"}]',
                            "s1", "u1", "DV-0001")
  expect_equal(db_log_events(con, ev), 1)
  expect_equal(db_log_events(con, NULL), 0L)
  e <- db_get_events(con)
  expect_equal(e$ts, "2026-01-01 10:00:00")
  expect_equal(nrow(db_get_events(con, since = "2026-01-02")), 0)
})

test_that("sync_status derives statuses after each appraisal step", {
  cfg <- test_cfg()
  con <- test_con()
  id <- reg(con, cfg, effort = "L", cost = 3)
  expect_equal(sync_status(con, cfg), id)
  expect_equal(db_get_initiatives(con, id)$status, "4M valuation")
  db_add_m4_line(con, id, m4_calculate("m_direct", list(mm_usd = 1), cfg))
  sync_status(con, cfg)
  expect_equal(db_get_initiatives(con, id)$status, "Expert review")
  db_add_review(con, id, "Approve", list(M = 1), 1, 3)
  sync_status(con, cfg)
  expect_equal(db_get_initiatives(con, id)$status, "Ready")
  expect_length(sync_status(con, cfg), 0)
})

test_that("sql_params rewrites placeholders for PostgreSQL only", {
  pg <- structure(list(), class = "PqConnection")
  expect_equal(digitalvalue:::sql_params(pg, "a = ? AND b = ?"), "a = $1 AND b = $2")
  expect_equal(digitalvalue:::sql_params(list(), "a = ?"), "a = ?")
})
